### PR TITLE
Re-sorted imports

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Using `isort`, all imports are auto-sorted. It's a standardized import sorting tool.

### CODE REVIEW

**Comment by PythonCoderAS** [comment]
Seems to be coveralls that's failing. I think it's mostly due to this being a forked repo.

**Comment by PythonCoderAS** [comment]
@LilSpazJoekp can you review this?

**Comment by LilSpazJoekp** [comment]
Did you run pre_push?

**Comment by PythonCoderAS** [comment]
> Did you run pre_push?

Linting is running fine, but Coveralls is failing. Probably because both repos are forks.

**Comment by PythonCoderAS** [comment]
I'll move this to main repo then.

**Pull request closed without merging**
